default_context:
  project_name: 'lms-fs'
  project_slug: 'lms-fs'
  domain_main: 'lms-fs.com'
  domain_staging: 'stag.lms-fs.com'
  docker_swarm_stack_name_main: 'lms-fs-com'
  docker_swarm_stack_name_staging: 'stag-lms-fs-com'
  secret_key: '4af06dfff0aa6f839865b78d3a5107b30c80fab31b217650eb1fb79e593a85a5'
  first_superuser: 'admin@lms-fs.com'
  first_superuser_password: 'Admin321!'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.lms-fs.com", "https://stag.lms-fs.com", "https://lms-fs.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@lms-fs.com'
  postgres_password: 'Admin321!'
  pgadmin_default_user: 'admin@lms-fs.com'
  pgadmin_default_user_password: 'Admin321!'
  traefik_constraint_tag: 'lms-fs.com'
  traefik_constraint_tag_staging: 'stag.lms-fs.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Admin321!'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
