"""change book_transaction

Revision ID: 208d393219cb
Revises: ed7ddb7ccb2a
Create Date: 2021-06-04 16:57:47.151053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208d393219cb'
down_revision = 'ed7ddb7ccb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booktransaction', sa.Column('customer_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'booktransaction', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booktransaction', type_='foreignkey')
    op.drop_column('booktransaction', 'customer_id')
    # ### end Alembic commands ###
