"""Book

Revision ID: 42a0c3cc2a8b
Revises: cda3b0ed6844
Create Date: 2021-05-30 08:29:10.494729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a0c3cc2a8b'
down_revision = 'cda3b0ed6844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('book_category_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'bookcategory', ['category_id'], ['id'])
    op.drop_column('book', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_category_fkey', 'book', 'bookcategory', ['category'], ['id'])
    op.drop_column('book', 'category_id')
    # ### end Alembic commands ###
