"""Update Customer

Revision ID: 4441a4cfb074
Revises: d77c209b6aa2
Create Date: 2021-05-30 04:53:04.978562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4441a4cfb074'
down_revision = 'd77c209b6aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_constraint('customer_owner_id_fkey', 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'customer', 'user', ['updated_by'], ['id'])
    op.drop_column('customer', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key('customer_owner_id_fkey', 'customer', 'user', ['owner_id'], ['id'])
    op.drop_column('customer', 'created_date')
    op.drop_column('customer', 'updated_by')
    op.drop_column('customer', 'created_by')
    # ### end Alembic commands ###
