"""Book Transaction

Revision ID: 589cc15795ec
Revises: 42a0c3cc2a8b
Create Date: 2021-05-30 13:50:18.168033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589cc15795ec'
down_revision = '42a0c3cc2a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booktransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('is_returned', sa.Boolean(), nullable=True),
    sa.Column('date_returned', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booktransaction_day'), 'booktransaction', ['day'], unique=False)
    op.create_index(op.f('ix_booktransaction_id'), 'booktransaction', ['id'], unique=False)
    op.create_index(op.f('ix_booktransaction_total'), 'booktransaction', ['total'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booktransaction_total'), table_name='booktransaction')
    op.drop_index(op.f('ix_booktransaction_id'), table_name='booktransaction')
    op.drop_index(op.f('ix_booktransaction_day'), table_name='booktransaction')
    op.drop_table('booktransaction')
    # ### end Alembic commands ###
