"""Book Category

Revision ID: 5cb01eb9cb5b
Revises: bcae13451209
Create Date: 2021-05-30 06:15:21.707711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb01eb9cb5b'
down_revision = 'bcae13451209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookcategory_desc'), 'bookcategory', ['desc'], unique=False)
    op.create_index(op.f('ix_bookcategory_id'), 'bookcategory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookcategory_id'), table_name='bookcategory')
    op.drop_index(op.f('ix_bookcategory_desc'), table_name='bookcategory')
    op.drop_table('bookcategory')
    # ### end Alembic commands ###
