"""Update Customer

Revision ID: bcae13451209
Revises: 4441a4cfb074
Create Date: 2021-05-30 05:36:55.225125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcae13451209'
down_revision = '4441a4cfb074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.alter_column('customer', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customer', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('customer', 'updated_date')
    # ### end Alembic commands ###
