"""Update Customer

Revision ID: d77c209b6aa2
Revises: e471a7af28c6
Create Date: 2021-05-27 12:49:59.421625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77c209b6aa2'
down_revision = 'e471a7af28c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
