"""change customer table

Revision ID: ed7ddb7ccb2a
Revises: f80c8ef4e9c0
Create Date: 2021-06-04 16:56:52.443281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7ddb7ccb2a'
down_revision = 'f80c8ef4e9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booktransaction_customer_id_fkey', 'booktransaction', type_='foreignkey')
    op.drop_column('booktransaction', 'customer_id')
    op.add_column('customer', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('major', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('batch_of_year', sa.Integer(), nullable=True))
    op.alter_column('customer', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('customer_id_seq'::regclass)"))
    op.drop_index('ix_customer_customer_id', table_name='customer')
    op.create_index(op.f('ix_customer_batch_of_year'), 'customer', ['batch_of_year'], unique=False)
    op.create_index(op.f('ix_customer_grade'), 'customer', ['grade'], unique=False)
    op.create_index(op.f('ix_customer_major'), 'customer', ['major'], unique=False)
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_customer_major'), table_name='customer')
    op.drop_index(op.f('ix_customer_grade'), table_name='customer')
    op.drop_index(op.f('ix_customer_batch_of_year'), table_name='customer')
    op.create_index('ix_customer_customer_id', 'customer', ['customer_id'], unique=False)
    op.alter_column('customer', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('customer_id_seq'::regclass)"))
    op.drop_column('customer', 'batch_of_year')
    op.drop_column('customer', 'major')
    op.drop_column('customer', 'grade')
    op.add_column('booktransaction', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('booktransaction_customer_id_fkey', 'booktransaction', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
