"""change books model

Revision ID: f80c8ef4e9c0
Revises: 589cc15795ec
Create Date: 2021-06-02 07:16:04.965379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80c8ef4e9c0'
down_revision = '589cc15795ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('book', sa.Column('isbn', sa.String(), nullable=True))
    op.drop_index('ix_book_desc', table_name='book')
    op.create_index(op.f('ix_book_isbn'), 'book', ['isbn'], unique=False)
    op.create_index(op.f('ix_book_publisher'), 'book', ['publisher'], unique=False)
    op.create_index(op.f('ix_book_year'), 'book', ['year'], unique=False)
    op.drop_column('book', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_book_year'), table_name='book')
    op.drop_index(op.f('ix_book_publisher'), table_name='book')
    op.drop_index(op.f('ix_book_isbn'), table_name='book')
    op.create_index('ix_book_desc', 'book', ['desc'], unique=False)
    op.drop_column('book', 'isbn')
    op.drop_column('book', 'publisher')
    op.drop_column('book', 'year')
    # ### end Alembic commands ###
